# Site settings
title: Kwon Dong Sung
email: 
description: > # this means to ignore newlines until "baseurl:"
  2020OSS
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kwondongsung.github.io" # the base hostname & protocol for your site
twitter_username: username
github_username: username

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
